- name: setup mysql server
  hosts: dbsrv
  become: true
  tasks:
    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: install python mysql
      yum:
        name: MySQL-python
        state: present


    - name: starting the mysql server
      service:
        name: mariadb
        state: started

    - name: creating the mysql database with accounts
      mysql_db:
        name: accounts
        state: present

    - name: creating the mysql user with admin
      mysql_user:
        name: admin
        password: admin123
        priv: '*.*:ALL,GRANT'
        state: present



